name: snowflake-devops-demo

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: dv48627.europe-west4.gcp
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange==3.7.0
          echo "SF_ACCOUNT is set to: $SF_ACCOUNT"
          echo "SF_USERNAME is set to: $SF_USERNAME"
          echo "SF_ROLE is set to: $SF_ROLE"
          echo "SF_WAREHOUSE is set to: $SF_WAREHOUSE"
          echo "SF_DATABASE is set to: $SF_DATABASE"
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/scripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c CHANGE_HISTORY --create-change-history-table
